version: "3.8"

services:

  server:
    build: .
    environment:
      - ENVIRONMENT=local
    volumes:
      - ./src:/src
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ems_db:/var/lib/postgresql/data

volumes:
  ems_db: